# Generated by Django 3.2.13 on 2022-05-14 07:20

from django.db import migrations, models
import helpdesk.models
import helpdesk.validators


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0036_add_attachment_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupattachment',
            name='file',
            field=models.FileField(max_length=1000, upload_to=helpdesk.models.attachment_path, validators=[helpdesk.validators.validate_file_extension, helpdesk.validators.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='kbiattachment',
            name='file',
            field=models.FileField(max_length=1000, upload_to=helpdesk.models.attachment_path, validators=[helpdesk.validators.validate_file_extension, helpdesk.validators.validate_file_size], verbose_name='File'),
        ),
    ]
