# Generated by Django 3.2.13 on 2022-05-15 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShorterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=20, unique=True)),
                ('long_link', models.TextField()),
                ('long_link_json', models.JSONField()),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
